##################################################################################################
# Main service receiving response from ingress
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  ports:
  - port: 80
#  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: greeting-service
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting-service-deployment-v1
spec:
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: greeting-service
        version: v1
    spec:
      containers:
      - name: greeting-service
        image: selcukc/greeting-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
##################################################################################################
# Dashboard receiving response from ingress
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  ports:
  - port: 80
#  - port: 8080
    name: http
    targetPort: 8070
  selector:
    app: dashboard
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-deployment-v1
spec:
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: dashboard
        version: v1
    spec:
      containers:
      - name: dashboard
        image: selcukc/dashboard:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8070
---
##################################################################################################
# Eureka Server
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server-deployment-v1
spec:
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: eureka-server
        version: v1
    spec:
      containers:
      - name: eureka-server
        image: selcukc/eureka-server:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
---
##################################################################################################
# services being called by main service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: name-service
  labels:
    app: name-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: name-service
  type: NodePort
#  - port: 80
#    name: http
#    targetPort: 8080
#  selector:
#    app: greeting-service
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name-service-deployment-v1
spec:
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: name-service
        version: v1
    spec:
      containers:
      - name: name-service
        image: selcukc/name-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
