spring:
  application:
    name: Greeting Service API

server:
  port: 8080

#backend:
#  ribbon:
#    eureka:
#      enabled: false
#    client:
#      enabled: true
#    ServerListRefreshInterval: 5000

#hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.threadpool.BackendCallThread.coreSize: 5

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
