spring:
  application:
    name: greeting-service

server:
  port: 8080

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:admin@eureka-server/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

#backend:
#  ribbon:
#    eureka:
#      enabled: false
#    client:
#      enabled: true
#    ServerListRefreshInterval: 5000

#hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.threadpool.BackendCallThread.coreSize: 5

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true