spring:
  application:
    name: eureka-server

server:
  port:
    8761

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
